name: Release Windows Binary

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write # This is required for creating releases and uploading assets

jobs:
  # Windows build
  windows-build:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Extract Cargo package name
        id: cargo-name
        shell: bash
        run: |
          PACKAGE_NAME=$(grep '^name = ' Cargo.toml | head -n 1 | sed 's/name = "\(.*\)"/\1/')
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "Package name from Cargo.toml: $PACKAGE_NAME"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Generate Cargo.lock
        run: cargo generate-lockfile

      - name: Build Release Binary
        run: cargo build --release

      - name: Copy Binary
        shell: powershell
        run: Copy-Item target\release\${{ env.package_name }}.exe -Destination ${{ github.event.repository.name }}-windows-x86_64.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: ${{ github.event.repository.name }}-windows-x86_64.exe
          draft: false
          prerelease: false
          generate_release_notes: true
