name: Release Unix Binaries

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write # This is required for creating releases and uploading assets

jobs:
  # Unix builds (Linux and macOS)
  unix-build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux build
          - os: ubuntu-latest
            asset_name: ${{ github.event.repository.name }}-linux-x86_64
            target: ''

          # macOS builds
          - os: macos-latest
            asset_name: ${{ github.event.repository.name }}-macos-x86_64
            target: ''

          # macOS ARM64 with cross-compilation
          - os: macos-latest
            asset_name: ${{ github.event.repository.name }}-macos-arm64
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v3

      - name: Extract Cargo package name
        id: cargo-name
        run: |
          PACKAGE_NAME=$(grep '^name = ' Cargo.toml | head -n 1 | sed 's/name = "\(.*\)"/\1/')
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "Package name from Cargo.toml: $PACKAGE_NAME"

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: ${{ github.event.repository.name }}
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          # Enable pushing to Cachix to speed up future builds
          pushFilter: "${{ github.event.repository.name }}.*"
          # Create a GitHub secret CACHIX_AUTH_TOKEN from cachix.org

      - name: Generate Cargo.lock
        run: nix develop -c cargo generate-lockfile

      # Install cross-compiler target if specified
      - name: Install Rust Target
        if: matrix.target != ''
        run: nix develop -c rustup target add ${{ matrix.target }}

      # Build for native architecture by default
      - name: Build Release Binary (Native)
        if: matrix.target == ''
        run: nix develop -c cargo build --release

      # Build for specified target if available
      - name: Build Release Binary (Target)
        if: matrix.target != ''
        run: nix develop -c cargo build --release --target ${{ matrix.target }}

      # Copy binary with appropriate name
      - name: Copy Native Binary
        if: matrix.target == ''
        run: cp target/release/${{ env.package_name }} ${{ matrix.asset_name }}

      - name: Copy Target Binary
        if: matrix.target != ''
        run: cp target/${{ matrix.target }}/release/${{ env.package_name }} ${{ matrix.asset_name }}

      # Make binary executable
      - name: Make binary executable
        run: chmod +x ${{ matrix.asset_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: ${{ matrix.asset_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
